// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0c6jW1Qi10Ba4SWl9TNwmZV6ztDE8r64',
    appId: '1:729529980286:web:a542fa0f75327e5412cf2f',
    messagingSenderId: '729529980286',
    projectId: 'todo-mdi',
    authDomain: 'todo-mdi.firebaseapp.com',
    storageBucket: 'todo-mdi.appspot.com', // Perbaikan versi
    measurementId: 'G-27WGSLPDZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBcF3eL9VTyQFcXSt9ZWoyTP4hk_Rk5ok',
    appId: '1:729529980286:android:626801462613b3cc12cf2f',
    messagingSenderId: '729529980286',
    projectId: 'todo-mdi',
    storageBucket: 'todo-mdi.appspot.com', // Perbaikan versi
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Gcn5ppEeUPwp21yJo8XE2QHlpy7MoxY',
    appId: '1:729529980286:ios:8e923210b67c36e212cf2f',
    messagingSenderId: '729529980286',
    projectId: 'todo-mdi',
    storageBucket: 'todo-mdi.appspot.com', // Perbaikan versi
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Gcn5ppEeUPwp21yJo8XE2QHlpy7MoxY',
    appId: '1:729529980286:ios:8e923210b67c36e212cf2f',
    messagingSenderId: '729529980286',
    projectId: 'todo-mdi',
    storageBucket: 'todo-mdi.appspot.com', // Perbaikan versi
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0c6jW1Qi10Ba4SWl9TNwmZV6ztDE8r64',
    appId: '1:729529980286:web:d713909a9daafc8812cf2f',
    messagingSenderId: '729529980286',
    projectId: 'todo-mdi',
    authDomain: 'todo-mdi.firebaseapp.com',
    storageBucket: 'todo-mdi.appspot.com', // Perbaikan versi
    measurementId: 'G-FBHC9K6NZP',
  );
}
